In [3]:
import numpy as np
import matplotlib.pyplot as plt

a = np.arange(12).reshape(3, 2, 2)
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [4]:
np.random.uniform(-5, -3)

-4.006231107433566

In [8]:
a = np.arange(4).reshape(2, 2)
b = np.arange(4).reshape(2, 2)
np.dot(a, b), a, b

(array([[ 2,  3],
        [ 6, 11]]),
 array([[0, 1],
        [2, 3]]),
 array([[0, 1],
        [2, 3]]))

In [6]:
import numpy as np 
a = np.array([1,2,3])
b = np.array([4,5,6])
## 数量积  使用np.dot或np.inner
print(np.dot(a,b))


32
