In [11]:
import torch

In [12]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(6).reshape(3, 2).transpose(1, 0)

In [13]:
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [14]:
b

tensor([[0, 2, 4],
        [1, 3, 5]])

In [15]:
torch.arange(6).reshape(3, 2)

tensor([[0, 1],
        [2, 3],
        [4, 5]])